### ISSUE TITLE
Using spaces in steps.name should give an error

### ISSUE THREAD

**Issue by karlowich** [refenv/cijoe#103]
The workflow below doesn't produce an error, but produces a report where the runlog for the step cannot be unfolded.
```
steps:
- name: io_size benchmark
  uses: io_size
```
Instead it should be:
```
steps:
- name: io_size_benchmark
  uses: io_size
```
Cijoe should give an error, ideally with a description of how to fix it.

**Comment by safl** [comment]
Addressed here: https://github.com/refenv/cijoe/pull/104
