### ISSUE TITLE
wrong error message if output dir exists and is populated

### ISSUE THREAD

**Issue by jwdevantier** [refenv/cijoe#31]
got:
```
# rnr: { OUTPUT: '/tmp/mytest.results' }
# ---------==========={[ CIJOE IS LOCKED ]}==========---------
# Looks like CIJOE is already running
# or, a previous run did unclean exit
# Clean up the target-system-under-test reboot / provision
# Then remove '/tmp/cijoe.lock' and start the runner again
# ---------==========={[ CIJOE IS LOCKED ]}==========---------
```

would expect a warning informing me that the output directory is populated with files from a previous test run, and that this is not ok.

**Comment by safl** [comment]
Thanks for reporting this.
A pre-release is cooking now, in five minutes you can try out the fix by installing it with:

```pip install --pre cijoe```

**Comment by safl** [comment]
Closing this as it should be fixed now.
