### ISSUE TITLE
Tests break if there is a space in the testsuites name 

### ISSUE THREAD

**Issue by Panky-codes** [refenv/cijoe#42]
when we have testsuite file, then there is no problem. 
If we are enumerating the testcases in testplan itself, then it breaks if there is a space:
```
testsuites:
  - name: sysfs parameters verify
    testcases:
    - sysfs_test.sh
```
with an error message:
```
# [2022-03-23 14:20:59] TESTPLAN_FPATH: '<path>/sanity_check.plan', does not exist
# [2022-03-23 14:20:59] rprtr:trun_fpath: path: '<path>//remove-po2/res_temp/trun.yml' does not exist
# [2022-03-23 14:20:59] rprtr: failed parsing command-line args
```
Instead of printing this obscure message, the cijoe should either explicitly mention that testsuite name cannot contain spaces or parse the name correctly with spaces.

**Comment by safl** [comment]
closing as cijoe has been re-implemented.
