### ISSUE TITLE
Multiple transports in a single configuration

### ISSUE THREAD

**Issue by safl** [refenv/cijoe#75]
It is not uncommon that one needs to utilize multiple transport endpoints, however, since **cijoe** does not support this, then there are awkward limitations. E.g. when setting up qemu-guests, then these commands should be able to run on any transport, but only "local" is possible, this is because the "ssh" transport is utilized to SSH into the machine itself.
Thus, it would be great to support multiple user-defined transports.

**Comment by NaddiNadja** [comment]
This has been fixed in #94
